name: Transfer Bot Run

on:
  schedule:
    - cron: '*/30 * * * *' # Her 30 dakikada bir otomatik çalışır
  workflow_dispatch: # Manuel çalıştırma butonu ve takım seçimi
    inputs:
      secilen_takim:
        description: 'Hangi takım için haber aransın?'
        required: true
        default: 'Fenerbahçe'
        type: choice
        options:
          - Fenerbahçe
          - Galatasaray
          - Beşiktaş
          - Trabzonspor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install tweepy requests

      - name: Run bot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          SECILEN_TAKIM: ${{ github.event.inputs.secilen_takim || 'Fenerbahçe' }}
          BOT_DURUMU: ${{ secrets.BOT_DURUMU }} # AÇ/KAPAT ŞALTERİ
        run: python bot.py
